#!/usr/bin/env python3
"""Generates blake2b_x3.h: three interleaved BLAKE2b-256 compressions of the
80-byte profile-0 input that differ only in message word 4 (nNonce|nonce2).

Interleaving three independent hashes keeps more of the core's integer ALUs
busy than one hash can. Round-0 G functions that don't involve word 4 or 5 are
precomputed once per job. Only output word 0 is produced; it is enough to
reject almost every nonce, and candidates are re-hashed in full.

Run: python3 gen_blake2b.py > blake2b_x3.h
"""

SIGMA = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
    [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
    [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
    [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
    [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
    [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
    [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
    [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
]
COLUMNS = [(0, 4, 8, 12), (1, 5, 9, 13), (2, 6, 10, 14), (3, 7, 11, 15),
           (0, 5, 10, 15), (1, 6, 11, 12), (2, 7, 8, 13), (3, 4, 9, 14)]
LANES = "abc"
PRECOMPUTED = (0, 1, 3)  # round-0 G calls using only words 0-3 and 6-7


def word(lane, i):
    if i >= 10:
        return None          # words 10..15 are zero
    if i == 4:
        return "m4" + lane   # the only word that differs between lanes
    return "m[%d]" % i


def g_steps(lane, a, b, c, d, x, y):
    A, B, C, D = ("v%d%s" % (k, lane) for k in (a, b, c, d))
    X, Y = word(lane, x), word(lane, y)
    return [
        "%s += %s%s;" % (A, B, " + " + X if X else ""), "%s = ROTR64(%s ^ %s, 32);" % (D, D, A),
        "%s += %s;" % (C, D), "%s = ROTR64(%s ^ %s, 24);" % (B, B, C),
        "%s += %s%s;" % (A, B, " + " + Y if Y else ""), "%s = ROTR64(%s ^ %s, 16);" % (D, D, A),
        "%s += %s;" % (C, D), "%s = ROTR64(%s ^ %s, 63);" % (B, B, C),
    ]


def body():
    out = []
    for r in range(12):
        s = SIGMA[r % 10]
        for g, (a, b, c, d) in enumerate(COLUMNS):
            if r == 0 and g in PRECOMPUTED:
                continue
            steps = [g_steps(L, a, b, c, d, s[2 * g], s[2 * g + 1]) for L in LANES]
            for k in range(8):
                out.extend("    " + st[k] for st in steps)
    return "\n".join(out)


def main():
    print("// Generated by gen_blake2b.py; do not edit.")
    print("#pragma once")
    print("#include <stdint.h>")
    print("#define ROTR64(x, n) (((x) >> (n)) | ((x) << (64 - (n))))")
    print("#define B2_H0 (0x6a09e667f3bcc908ULL ^ 0x01010020ULL)")
    print()
    print("// State after the round-0 G calls that don't touch words 4/5; once per job.")
    print("static inline void blake2b80_precompute(const uint64_t m[10], uint64_t pre[16])")
    print("{")
    print("    static const uint64_t iv[8] = {")
    print("        0x6a09e667f3bcc908ULL, 0xbb67ae8584caa73bULL, 0x3c6ef372fe94f82bULL, 0xa54ff53a5f1d36f1ULL,")
    print("        0x510e527fade682d1ULL, 0x9b05688c2b3e6c1fULL, 0x1f83d9abfb41bd6bULL, 0x5be0cd19137e2179ULL};")
    print("    uint64_t v0a = B2_H0, v1a = iv[1], v2a = iv[2], v3a = iv[3], v4a = iv[4], v5a = iv[5], v6a = iv[6], v7a = iv[7];")
    print("    uint64_t v8a = iv[0], v9a = iv[1], v10a = iv[2], v11a = iv[3], v12a = iv[4] ^ 80, v13a = iv[5], v14a = ~iv[6], v15a = iv[7];")
    for g in PRECOMPUTED:
        a, b, c, d = COLUMNS[g]
        for st in g_steps("a", a, b, c, d, SIGMA[0][2 * g], SIGMA[0][2 * g + 1]):
            print("    " + st)
    print("    " + " ".join("pre[%d] = v%da;" % (i, i) for i in range(16)))
    print("}")
    print()
    print("// Output word 0 (bytes 0..7) of three BLAKE2b-256 hashes differing only in word 4.")
    print("static inline void blake2b80_x3_word0(const uint64_t m[10], const uint64_t pre[16],")
    print("                                      uint64_t m4a, uint64_t m4b, uint64_t m4c, uint64_t out[3])")
    print("{")
    for i in range(16):
        print("    uint64_t " + ", ".join("v%d%s = pre[%d]" % (i, L, i) for L in LANES) + ";")
    print(body())
    for k, L in enumerate(LANES):
        print("    out[%d] = B2_H0 ^ v0%s ^ v8%s;" % (k, L, L))
    print("}")


if __name__ == "__main__":
    main()
