#!/usr/bin/env python3
"""Generates GPUKernel.swift: the Metal (GPU) hashing kernel, as Swift source text.

Same job as the CPU kernels (output word 0 of the BLAKE2b of the 80-byte input
for many values of word 4), with the operation list taken from
gen_blake2b_arm64.py so the kernels can't drift apart.

Each GPU thread hashes NONCES_PER_THREAD consecutive nonces: word 4 = base +
gid * NONCES_PER_THREAD + k. 64-bit words are kept as (lo, hi) 32-bit halves,
which the GPU handles natively; rotating by 32 is then just a swap. A nonce whose
word 0 passes the quick check is appended to `hits`; the CPU re-checks every hit
with the full hash before it is used. In debug mode word 0 of every nonce is
written to `words` instead (self-test).

Run: python3 gen_blake2b_metal.py > ../Sources/MinerCore/GPUKernel.swift
"""
import importlib.util
import os

spec = importlib.util.spec_from_file_location(
    "arm64", os.path.join(os.path.dirname(os.path.abspath(__file__)), "gen_blake2b_arm64.py"))
arm64 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(arm64)

NONCES_PER_THREAD = 16
MAX_HITS = 1024


def body():
    out = []
    for op in arm64.ir():
        if op[0] == "add":
            src = "v%d" % op[2][1] if op[2][0] == "v" else ("m4" if op[2][1] == 4 else "m%d" % op[2][1])
            out.append("v%d = add64(v%d, %s);" % (op[1], op[1], src))
        else:
            out.append("v%d = xr%d(v%d, v%d);" % (op[1], op[3], op[1], op[2]))
    return "\n".join("            " + line for line in out)


def kernel():
    load_m = "\n".join("    const uint2 m%d = split(P.m[%d]);" % (i, i) for i in range(10) if i != 4)
    load_v = "\n".join("        uint2 v%d = split(P.pre[%d]);" % (i, i) for i in range(16))
    return """#include <metal_stdlib>
using namespace metal;

// Must match GPUEngine.Params.
struct Params {
    ulong m[10];
    ulong pre[16];
    ulong base;
    ulong target0;  // most significant 64 bits of the target
    uint debug;
};

static inline uint bswap32(uint x) { return (x >> 24) | ((x >> 8) & 0xff00u) | ((x << 8) & 0xff0000u) | (x << 24); }
static inline uint2 split(ulong x) { return as_type<uint2>(x); }
static inline uint2 add64(uint2 a, uint2 b) { uint lo = a.x + b.x; return uint2(lo, a.y + b.y + (lo < a.x ? 1u : 0u)); }
// d = ror64(d ^ a, n) on (lo, hi) halves.
static inline uint2 xr32(uint2 d, uint2 a) { uint2 t = d ^ a; return uint2(t.y, t.x); }
static inline uint2 xr24(uint2 d, uint2 a) { uint2 t = d ^ a; return uint2((t.x >> 24) | (t.y << 8), (t.y >> 24) | (t.x << 8)); }
static inline uint2 xr16(uint2 d, uint2 a) { uint2 t = d ^ a; return uint2((t.x >> 16) | (t.y << 16), (t.y >> 16) | (t.x << 16)); }
static inline uint2 xr63(uint2 d, uint2 a) { uint2 t = d ^ a; return uint2((t.x << 1) | (t.y >> 31), (t.y << 1) | (t.x >> 31)); }

kernel void blake2b80(constant Params &P [[buffer(0)]],
                      device atomic_uint *hitCount [[buffer(1)]],
                      device ulong *hits [[buffer(2)]],
                      device ulong *words [[buffer(3)]],
                      uint gid [[thread_position_in_grid]])
{
    const ulong H0 = 0x%xUL;
%s
    for (uint k = 0; k < %d; ++k) {
        const ulong nonce = P.base + ulong(gid) * %d + k;
        const uint2 m4 = split(nonce);
%s
        {
%s
        }
        const ulong w = H0 ^ as_type<ulong>(v0) ^ as_type<ulong>(v8);
        if (P.debug) {
            words[ulong(gid) * %d + k] = w;
            continue;
        }
        // The hash's first 8 bytes, read big-endian, against the target's top word.
        const uint2 h = as_type<uint2>(w);
        const ulong be = (ulong(bswap32(h.x)) << 32) | bswap32(h.y);
        if (be <= P.target0) {
            const uint i = atomic_fetch_add_explicit(hitCount, 1, memory_order_relaxed);
            if (i < %d) hits[i] = nonce;
        }
    }
}
""" % (arm64.H0, load_m, NONCES_PER_THREAD, NONCES_PER_THREAD, load_v, body(), NONCES_PER_THREAD, MAX_HITS)


def main():
    src = kernel()
    print("// Generated by scripts/gen_blake2b_metal.py; do not edit.")
    print()
    print("enum GPUKernel {")
    print("    static let noncesPerThread = %d" % NONCES_PER_THREAD)
    print("    static let maxHits = %d" % MAX_HITS)
    print("    static let source = #\"\"\"")
    print(src.rstrip("\n"))
    print("\"\"\"#")
    print("}")


if __name__ == "__main__":
    main()
